/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.borrowDAO;
import DAO.categoryDAO;
import DAO.loginDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.borrow;
import model.login;

/**
 *
 * @author hoand
 */
public class FrmBorrowHistory extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmBorrowHistory
     */
    DefaultTableModel model;
    check check = new check();

    public FrmBorrowHistory() {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel();
        showTable();

    }

    void showTable() {
        clearTable();
        borrowDAO bDAO = new borrowDAO();
        ArrayList<borrow> list = bDAO.getAllbook();
        for (borrow o : list) {
            String status = "Chưa trả";
            if (o.isStatus()) {
                status = "Đã trả";
            }
            Object[] a = {o.getId(), o.getBookId(), o.getQuantity(), o.getStudentName(), o.getStudentClass(), o.getStudentID(), o.getTimeGet(), status};
            model.addRow(a);
        }
    }

    void showTableByStudentName(String name) {
        clearTable();
        borrowDAO bDAO = new borrowDAO();
        ArrayList<borrow> list = bDAO.getAllbook(name);
        if (list.size() == 0) {
            JOptionPane.showMessageDialog(null, "Không tìm thấy!");
            return;
        }
        for (borrow o : list) {
            String status = "Chưa trả";
            if (o.isStatus()) {
                status = "Đã trả";
            }
            Object[] a = {o.getId(), o.getBookId(), o.getQuantity(), o.getStudentName(), o.getStudentClass(), o.getStudentID(), o.getTimeGet(), status};
            model.addRow(a);
        }
    }

    void showTableByStudentId(String id) {
        clearTable();
        borrowDAO bDAO = new borrowDAO();
        ArrayList<borrow> list = bDAO.getAllbookById(id);
        if (list.size() == 0) {
            JOptionPane.showMessageDialog(null, "Không tìm thấy!");
            return;
        }
        for (borrow o : list) {
            String status = "Chưa trả";
            if (o.isStatus()) {
                status = "Đã trả";
            }
            Object[] a = {o.getId(), o.getBookId(), o.getQuantity(), o.getStudentName(), o.getStudentClass(), o.getStudentID(), o.getTimeGet(), status};
            model.addRow(a);
        }
    }

    void clearTable() {
        model.getDataVector().removeAllElements();
    }

    boolean status;

    void ShowtablebyRdButton(boolean status) {
        clearTable();
        borrowDAO bDAO = new borrowDAO();
        ArrayList<borrow> list = bDAO.getAllbook(status);
        if (list.size() == 0) {
            JOptionPane.showMessageDialog(null, "Không tìm thấy!");
            return;
        }
        for (borrow o : list) {
            String sta = "Chưa trả";
            if (o.isStatus()) {
                sta = "Đã trả";
            }
            Object[] a = {o.getId(), o.getBookId(), o.getQuantity(), o.getStudentName(), o.getStudentClass(), o.getStudentID(), o.getTimeGet(), sta};
            model.addRow(a);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtSearchByName = new javax.swing.JTextField();
        btnSearchByName = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rdGiveBack = new javax.swing.JRadioButton();
        rdNotGiveBack = new javax.swing.JRadioButton();
        btnChangeStatus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        txtSearchById = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSearchById = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã sách", "Số lượng", "Tên SV", "Lớp", "Mã SV", "Thời gian", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnSearchByName.setText("Tìm");
        btnSearchByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên SV");

        buttonGroup1.add(rdGiveBack);
        rdGiveBack.setText("Đã trả");
        rdGiveBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdGiveBackActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdNotGiveBack);
        rdNotGiveBack.setText("Chưa trả");
        rdNotGiveBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNotGiveBackActionPerformed(evt);
            }
        });

        btnChangeStatus.setText("Chuyển trạng Thái");
        btnChangeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeStatusActionPerformed(evt);
            }
        });

        jLabel2.setText("Chọn 1 hàng để chuyển trạng thái 'Đã trả");

        jLabel3.setText("hoặc 'Chưa trả'");

        btnRemove.setText("Xóa");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jLabel4.setText("chọn 1 hàng để xóa lịch sử");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel5.setText("Mã SV");

        btnSearchById.setText("Tìm");
        btnSearchById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                        .addComponent(txtSearchByName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnSearchByName, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSearchById, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rdNotGiveBack)
                                        .addComponent(rdGiveBack)
                                        .addComponent(btnChangeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(btnRemove)
                                        .addComponent(jLabel4))
                                    .addComponent(btnSearchById, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 148, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchByName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchByName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchById, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchById)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdGiveBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdNotGiveBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChangeStatus)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByNameActionPerformed
        String txt = txtSearchByName.getText();
        showTableByStudentName(txt);
    }//GEN-LAST:event_btnSearchByNameActionPerformed

    private void rdGiveBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdGiveBackActionPerformed
        status = true;
        ShowtablebyRdButton(status);
    }//GEN-LAST:event_rdGiveBackActionPerformed

    private void rdNotGiveBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNotGiveBackActionPerformed
        status = false;
        ShowtablebyRdButton(status);
    }//GEN-LAST:event_rdNotGiveBackActionPerformed

    private void btnChangeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeStatusActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;

        String bId = "";
        String status = "";
        try {
            int row = jTable1.getSelectedRow();
            bId = jTable1.getValueAt(row, 0).toString().trim();
            status = jTable1.getValueAt(row, 7).toString().trim();
            if (status.equals("Chưa trả")) {
                status = "Đã trả";
            } else {
                status = "Chưa trả";
            }
            dialogButton = JOptionPane.showConfirmDialog(null, "bạn có muốn chuyển trạng thái của " + bId + " thành " + status + "?", "Warning", dialogButton);
            if (dialogButton == JOptionPane.YES_OPTION) {

            } else {
                return;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Bạn phải chọn một hàng trong bảng!");
            return;
        }

        try {
            borrowDAO bDAO = new borrowDAO();
            if (status.equals("Đã trả")) {
                bDAO.setStatus(Integer.parseInt(bId), true);
                JOptionPane.showMessageDialog(null, "Thành công!");
            } else {
                bDAO.setStatus(Integer.parseInt(bId), false);
                JOptionPane.showMessageDialog(null, "Thành công!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Thất bại!");
        }
        showTable();


    }//GEN-LAST:event_btnChangeStatusActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;

        String remove = "";
        try {
            int row = jTable1.getSelectedRow();
            remove = jTable1.getValueAt(row, 0).toString().trim();
            dialogButton = JOptionPane.showConfirmDialog(null, "bạn có muốn xóa " + remove + "?", "Warning", dialogButton);
            if (dialogButton == JOptionPane.YES_OPTION) {

            } else {
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Bạn phải chọn một hàng trong bảng!");
            return;
        }

        if (check.checkvalidString(remove)) {

            borrowDAO bDAO = new borrowDAO();
            if (bDAO.remove(Integer.parseInt(remove))) {
                JOptionPane.showMessageDialog(null, "xoá thành công!");
            } else {
                JOptionPane.showMessageDialog(null, "lỗi!");
            }

        }
        showTable();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSearchByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByIdActionPerformed
        String txt = txtSearchById.getText();
        if (!check.checkvalidString(txt)) {
            JOptionPane.showMessageDialog(null, "Không hợp lệ!");
            return;
        }
        showTableByStudentId(txt);
    }//GEN-LAST:event_btnSearchByIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeStatus;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearchById;
    private javax.swing.JButton btnSearchByName;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rdGiveBack;
    private javax.swing.JRadioButton rdNotGiveBack;
    private javax.swing.JTextField txtSearchById;
    private javax.swing.JTextField txtSearchByName;
    // End of variables declaration//GEN-END:variables
}
